Use aws provider default_tags
Azure/telescope pull request #339
Opened 2024-10-16 18:12 UTC by rafael-mendes-pereira

Introduce the [aws provider default_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#propagating-tags-to-all-resources) to propagate the required tags to all supported resources.  

This feature is important to enforce tags, such as, `owner` and `deletion_due_time` , which are used for the cost tracking and garbage collection.

Note: this feature has some limitations: 
1. No support to [aws_autoscaling_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group)
2. No support to computed values (e.g. `timestamp()`). See Terraform issue [#19583](https://github.com/hashicorp/terraform-provider-aws/issues/19583#issuecomment-1561337902). 
To overtake this issue, this change replaces  the `timestamp()` function with the time resources: `time_static` and `time_offset`. (note that Terraform [does not recommend](https://developer.hashicorp.com/terraform/language/functions/timestamp) to use `timestamp()` in resources attributes)

2024-10-16 18:50 UTC, anson627 submitted a review, later dismissed

2024-10-16 18:51 UTC, anson627 commented
need fix failed terraform validation

2024-10-17 19:46 UTC, rafael-mendes-pereira commented
> need fix failed terraform validation

Done. Thanks

2024-10-17 20:04 UTC, alyssa1303 reviewed
We should do a test run with internal pipelines to make sure no breaking change

2024-10-17 20:04 UTC, alyssa1303 commented on .github/workflows/terraform-validation.yml
>            echo "INPUT_JSON=$INPUT_JSON_STRING" >> "$GITHUB_ENV"
Maybe set this like RUN_ID?

2024-10-17 20:04 UTC, alyssa1303 commented on modules/terraform/aws/README.md
> -      }' | jq 'with_entries(select(.value != null and .value != ""))')
Same here. Set in like RUN_ID and use as arg instead of extending?

2024-10-17 20:04 UTC, alyssa1303 commented on modules/terraform/aws/README.md
> -terraform plan -var json_input=$(echo $INPUT_JSON | jq -c .) -var-file $TERRAFORM_INPUT_FILE
While are they needed here if INPUT_JSON already has current_time?

2024-10-17 20:04 UTC, alyssa1303 commented on modules/terraform/aws/main.tf
> +    "creation_time"     = local.current_time                              # note: should not use timestamp() since it is a computed value
Can it be part of json_input like run_id?

2024-10-18 17:54 UTC, alyssa1303 commented on steps/terraform/run-command.yml
> +        if [[ "$CLOUD" == "aws" ]]; then
I think we're trying to avoid doing this if possible since this is a shared step. What I meant by not appending to json_input is to first define it, then use it as an argument like this
```
CURRENT_TIME=$(date -uIseconds | sed 's/+00:00/Z/')
INPUT_JSON=$(jq -n \
      --arg run_id $RUN_ID \
      --arg current_time $CURRENT_TIME \
      --arg region $REGION \
      '{
      run_id: $run_id,
      current_time: $current_time,
      region: $region
      }' | jq 'with_entries(select(.value != null and .value != ""))')
```

So still the old way but do it like RUN_ID instead of appending after jq. Sorry if my explanation wasn't clear earlier.

2024-10-18 18:31 UTC, alyssa1303 approved these changes

2024-10-21 13:23 UTC, sumanthreddy29 requested changes

2024-10-21 13:23 UTC, sumanthreddy29 commented on modules/terraform/aws/karpenter/main.tf
> -  tags = {
these tags are for open source karpenter module. We will keep the same way they are right now as we are not using it currently.

2024-10-21 13:23 UTC, sumanthreddy29 commented on modules/terraform/aws/karpenter/variables.tf
> -variable "owner" {
These are required for karpenter open source module as this module becomes the main module when we use open source karpenter.

2024-10-21 13:23 UTC, sumanthreddy29 commented on modules/terraform/aws/virtual-network/main.tf
> -  tags                = merge(var.tags, { "role" = var.network_config.role })
In networking module, we still have lot tag references

2024-10-25 11:14 UTC, rafael-mendes-pereira commented on steps/terraform/run-command.yml
> +        if [[ "$CLOUD" == "aws" ]]; then
As we talked in Teams, we need to make sure that the current time is updated when the resources are provisioned. Having it in the input json would require to update the json every time someone runs 'terraform apply'. To prevent that and make the code easier to maintain, I added the `current_time` as another input variable for terraform commands.

2024-10-25 14:29 UTC, rafael-mendes-pereira commented
> We should do a test run with internal pipelines to make sure no breaking change

I changed the PR to revert the tags removal in the public modules until we add the
default_tags to the internal repo.

2024-10-31 10:45 UTC, merged