Add Telescope Metadata to the results
Azure/telescope pull request #380
Opened 2024-11-04 17:07 UTC by sumanthreddy29

1. Collect Telescope Metadata.
2. Update final results schema to have metadata and results.

2024-11-18 19:47 UTC, sumanthreddy29 commented on pipelines/perf-eval/node-auto-provisioning-benchmark-nodes10-pods100.yml
> -  SCENARIO_VERSION: main
Revert test changes

2024-11-21 16:19 UTC, alyssa1303 commented on steps/cloud/azure/upload-storage-account.yml
> +      SUBFOLDER: ${{ parameters.subfolder }}
I don't think it's a good idea. Doesn't this mean the SCENARIO_VERSION is no longer usable? It'll confuse users and they can't find where to look for blobs to check results correctly. For example, when someone sets scenario_version to a tag, it just got push to somewhere else? This also means that we no longer allow the flexibility of using something else other than 'main' as scenario_version for scheduled run? What if users want to change schema, do they always have to delete and recreate the table?

2024-11-21 16:19 UTC, alyssa1303 commented on steps/collect-telescope-metadata.yml
> +    jq --argfile telescope_metadata $(TELESCOPE_METADATA_FILE) \
I recommend testing it with test that produce a big jq result file like compute or iperf3 to see if jq can handle it or not

2024-11-21 16:19 UTC, alyssa1303 commented on steps/setup-tests.yml
> +    telescope_metadata=$(jq -n \
Why do we have to set it here?

2024-11-21 16:19 UTC, alyssa1303 commented on steps/collect-telescope-metadata.yml
> +- ${{ if eq(variables['Build.SourceBranchName'], 'add-telescope-metadata') }}:
What is this step for?

2024-11-21 16:22 UTC, sumanthreddy29 commented on steps/collect-telescope-metadata.yml
> +- ${{ if eq(variables['Build.SourceBranchName'], 'add-telescope-metadata') }}:
We don't want to collect data that is not from main branch. For testing I added my branch here.

2024-11-21 16:24 UTC, sumanthreddy29 commented on steps/setup-tests.yml
> +    telescope_metadata=$(jq -n \
Removed

2024-11-21 16:37 UTC, sumanthreddy29 commented on steps/cloud/azure/upload-storage-account.yml
> +      SUBFOLDER: ${{ parameters.subfolder }}
1. `SCENARIO_VERSION` is used when we run a manual/scheduled trigger against main branch which is part of else statement. 
2. If someone sets `scenario_version`as a tag, we push the data to tag folder itself if the run is triggered from main branch. 
3. Let's say when user creates a test branch and uses that test branch name as `scenario_version` with scheduled run we push the data to the branch which triggered the pipeline. Only restriction is they have to set the scenario version and branch name same here which allows the flexibility of using any value for `scenario_version`

2024-11-21 16:53 UTC, alyssa1303 commented on steps/collect-telescope-metadata.yml
> +- ${{ if eq(variables['Build.SourceBranchName'], 'add-telescope-metadata') }}:
Why don't we want it? Doesn't that mean results we see in testing is different from testing we see in main? I think we should make it consistent so people know for sure what to expect in the data

2024-11-21 17:11 UTC, sumanthreddy29 commented on steps/cloud/azure/upload-storage-account.yml
> +      SUBFOLDER: ${{ parameters.subfolder }}
reverted this change

2024-11-21 17:14 UTC, sumanthreddy29 commented on steps/collect-telescope-metadata.yml
> +- ${{ if eq(variables['Build.SourceBranchName'], 'add-telescope-metadata') }}:
this step only uploads metadata for the run which we use for building the dashboard. I thought it's better not to collect.

2024-11-21 18:31 UTC, sumanthreddy29 commented on steps/collect-telescope-metadata.yml
> +    jq --argfile telescope_metadata $(TELESCOPE_METADATA_FILE) \
Tested with compute and iperf test cases. Updated the internal post with the links

2024-11-22 17:11 UTC, alyssa1303 commented on steps/collect-telescope-metadata.yml
> +      --arg scenario_name "$SCENARIO_NAME" \
Can we collect GitHub branch and commit too for ADO runs? I believe this will only collect ADO branch and commit if for all internal pipelines

2024-11-22 17:14 UTC, alyssa1303 commented on steps/collect-telescope-metadata.yml
> +      --arg scenario_name "$SCENARIO_NAME" \
It'll be useful if an external to track if external change break internal pipelines and how often it happen to improve our monitoring

2024-11-22 17:25 UTC, sumanthreddy29 commented on steps/collect-telescope-metadata.yml
> +      --arg scenario_name "$SCENARIO_NAME" \
Sure. I added the change. I will test and update the PR and the Teams thread.

2024-11-22 20:55 UTC, alyssa1303 approved these changes

2024-11-22 20:57 UTC, alyssa1303 requested changes
Actual just saw 1 error "line 37: Build.CronSchedule.DisplayName: command not found". Is this resolved?

2024-11-22 21:59 UTC, alyssa1303 approved these changes

2024-11-22 22:03 UTC, merged